/**
 * print-brief.ts
 *
 * Reads today's brief.md, converts it to print-ready plain text,
 * and sends it to the configured network printer via lp/lpr.
 *
 * Requires: cups (lp command) installed on the Pi.
 * Install: sudo apt install cups cups-client
 *
 * To find your printer name: lpstat -p -d
 *                             lpinfo -v  (shows network printers)
 */

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import * as dotenv from "dotenv";

dotenv.config({ path: path.resolve(__dirname, "../.env") });

const DATA_DIR = process.env.DATA_DIR ?? path.resolve(__dirname, "../data");
const TIMEZONE = process.env.TIMEZONE ?? "America/Chicago";
const PRINTER_NAME = process.env.PRINTER_NAME;
const PRINTER_OPTIONS = process.env.PRINTER_OPTIONS ?? "";

function toLocalDateString(date: Date, tz: string): string {
  return date.toLocaleDateString("en-CA", { timeZone: tz });
}

/**
 * Convert markdown to clean plain text suitable for printing.
 * Handles headers, bold, bullets, and horizontal rules.
 */
function markdownToText(md: string): string {
  return md
    // H2 headers → underlined with ═
    .replace(/^## (.+)$/gm, (_, title) => {
      const line = "═".repeat(Math.min(title.length + 2, 60));
      return `\n${line}\n  ${title.toUpperCase()}\n${line}`;
    })
    // H3 headers → underlined with ─
    .replace(/^### (.+)$/gm, (_, title) => {
      const line = "─".repeat(Math.min(title.length + 2, 50));
      return `\n${title}\n${line}`;
    })
    // Bold **text** → CAPS or just strip markers
    .replace(/\*\*(.+?)\*\*/g, "$1")
    // Italic *text* → strip markers
    .replace(/\*(.+?)\*/g, "$1")
    // Inline code → strip backticks
    .replace(/`(.+?)`/g, "$1")
    // Code fences → strip
    .replace(/^```.*$/gm, "")
    // Collapse 3+ blank lines to 2
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/**
 * Add a header banner and footer to the print output.
 */
function addPrintWrapper(text: string, date: string): string {
  const now = new Date();
  const printedAt = now.toLocaleTimeString("en-US", {
    timeZone: TIMEZONE,
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });

  const banner = [
    "╔══════════════════════════════════════════════════════════╗",
    `║  DAILY BRIEF — ${date.padEnd(42)}║`,
    `║  Printed at ${printedAt.padEnd(47)}║`,
    "╚══════════════════════════════════════════════════════════╝",
    "",
  ].join("\n");

  const footer = [
    "",
    "──────────────────────────────────────────────────────────",
    `End of brief · ${date} · Generated by daily-brief on Pi`,
    "",
  ].join("\n");

  return banner + text + footer;
}

async function main() {
  if (!PRINTER_NAME) {
    console.error("[print-brief] PRINTER_NAME not set in .env");
    console.error("[print-brief] Run `lpstat -p` to find your printer name.");
    process.exit(1);
  }

  const now = new Date();
  const today = toLocalDateString(now, TIMEZONE);
  const dir = path.join(DATA_DIR, today);
  const briefPath = path.join(dir, "brief.md");
  const printPath = path.join(dir, "brief.txt");

  if (!fs.existsSync(briefPath)) {
    console.error(`[print-brief] No brief found at ${briefPath}`);
    console.error(`[print-brief] Run generate-brief.ts first.`);
    process.exit(1);
  }

  const markdown = fs.readFileSync(briefPath, "utf8");
  const plainText = markdownToText(markdown);
  const printReady = addPrintWrapper(plainText, today);

  fs.writeFileSync(printPath, printReady);
  console.log(`[print-brief] Wrote print-ready text to ${printPath}`);

  // Check if printer is reachable
  try {
    execSync(`lpstat -p "${PRINTER_NAME}" 2>&1`, { timeout: 10_000 });
  } catch {
    console.warn(`[print-brief] ⚠ Could not verify printer "${PRINTER_NAME}" — attempting anyway.`);
  }

  // Build lp command
  const optStr = PRINTER_OPTIONS ? ` ${PRINTER_OPTIONS}` : "";
  const lpCmd = `lp -d "${PRINTER_NAME}"${optStr} -t "Daily Brief ${today}" "${printPath}"`;

  console.log(`[print-brief] Sending to printer: ${PRINTER_NAME}`);
  console.log(`[print-brief] Command: ${lpCmd}`);

  try {
    const result = execSync(lpCmd, { timeout: 30_000 }).toString().trim();
    console.log(`[print-brief] ✓ ${result}`);
  } catch (err: any) {
    console.error("[print-brief] Print failed:");
    console.error(err.stderr?.toString() ?? err.message);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error("[print-brief] ERROR:", err.message);
  process.exit(1);
});